name: JCB forwarder CI

on:
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t jcb-forwarder -f Dockerfile .
      - name: Tags
        run: |
          docker tag jcb-forwarder ${{ secrets.DOCKER_USER }}/jcb-forwarder:${{ github.sha }}
          docker tag jcb-forwarder ${{ secrets.DOCKER_USER }}/jcb-forwarder:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/jcb-forwarder:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/jcb-forwarder:latest
